version: '3'


services:
  # Data Generator
  dg:
    build: ./data_generator
    image: dg:0.0.1
    volumes:
      - ./data_generator/code:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 main.py

  # Counter of incedents
  ic:
    build: ./counter
    image: ic:0.0.1
    volumes:
      - ./counter/code:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 main.py
