version: '3'


services:
  # Counter of incedents
  ic:
    build: ./counter
    image: ic:0.0.1
    volumes:
      - ./counter/code:/app
      - ~/projects/data/inccounter:/data
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "python3", "main.py", "--input_file=/some/data", "--output_file=/some/new/data", "-dt=0.5" ]

  # Data Generator
  dg:
    build: ./data_generator
    image: dg:0.0.1
    volumes:
      - ./data_generator/code:/app
      - ~/projects/data/inccounter:/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 main.py
