version: '3'


services:
  # Counter of incedents
  ic:
    build: ./counter
    image: ic:0.0.1
    volumes:
      - ./counter/code:/app
      - ~/projects/data/inccounter:/data    # data directory
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "python3", "main.py", "--input_file=/data/incedents.csv", "--output_file=/data/counts.csv", "-dt=0.3" ]

  # Data Generator
  dg:
    build: ./data_generator
    image: dg:0.0.1
    volumes:
      - ./data_generator/code:/app
      - ~/projects/data/inccounter:/data    # data directory
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "python3", "main.py", "--output_file=/data/incedents.csv", "-m=2", "-n=1000000" ]
